name: Run API Tests

on: [push, pull_request]  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3  

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  

      - name: Instalar dependências
        run: pip install requests 

      - name: Rodar testes
        run: python tests/test_api.py 